name: Run Prettier
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Change script permissions
        run: chmod +x path/to/your/script.sh
        
      - name: Run Script
        run: npm run prettier:format
  